apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: sqlhost                           # data field to populate
      objectName: sqlhost                        # name of the mounted content to sync; this could be the object name or the object alias
    - key: sqlusername                           # data field to populate
      objectName: sqlusername                        # name of the mounted content to sync; this could be the object name or the object alias
    - key: sqlpassword                           # data field to populate
      objectName: sqlpassword                        # name of the mounted content to sync; this could be the object name or the object alias      
    secretName: sql-secret                     # name of the Kubernetes secret object
    type: Opaque                              # type of Kubernetes secret object (for example, Opaque, kubernetes.io/tls)
