apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
    - port: 80 # SERVICE exposed port
      name: http # SERVICE port name
      protocol: TCP # The protocol the SERVICE will listen to
      targetPort: 80 # Port to forward to in the POD
---
kind: Service
apiVersion: v1
metadata:
  name: trips-external
spec:
  type: ExternalName
  externalName: trips.api.svc.cluster.local
  ports:
  - port: 80
    name: http      
